---
title: HRodberg
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
tagline: Portfolio
description: Portfolio
url: https://hrodberg.github.io/
baseurl: https://hrodberg.github.io
author:
  name: Hazen Rodberg-Tatton
paginate: 5
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
version: 3.7.0
sidebar_home_link: true
github:
  repo: https://github.com/HRodberg
